require("dotenv").config();
const nodemailer = require("nodemailer");

console.log("🔍 Testing SMTP Connection...\n");
console.log("SMTP Config:");
console.log("  Host:", process.env.SMTP_HOST);
console.log("  Port:", process.env.SMTP_PORT);
console.log("  User:", process.env.SMTP_USER);
console.log("  From:", process.env.EMAIL_FROM);
console.log();

const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT),
    secure: true,
    auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
    },
});

// Test 1: Verify connection
console.log("Test 1: Verifying SMTP connection...");
transporter.verify()
    .then(() => {
        console.log("✅ SMTP connection verified!\n");
        
        // Test 2: Send a real test email
        console.log("Test 2: Sending test email to harshwardhan@hf.org.in...");
        return transporter.sendMail({
            from: process.env.EMAIL_FROM || "no-reply@humanityfounders.com",
            to: "harshwardhan@hf.org.in",
            subject: "Test Email - Email Service Diagnostic",
            html: `
                <h2>Email Service Test</h2>
                <p>This is a test email sent at ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST.</p>
                <p>If you received this, the email service is working correctly.</p>
                <hr>
                <p><small>Generated by quickEmailTest.js</small></p>
            `
        });
    })
    .then((info) => {
        console.log("✅ Test email sent successfully!");
        console.log("   Message ID:", info.messageId);
        console.log("   Response:", info.response);
        console.log("\n✅ All tests passed! Email service is working.");
        process.exit(0);
    })
    .catch((error) => {
        console.error("❌ Email test failed:");
        console.error(error);
        process.exit(1);
    });
